version: '3.8'

services:
  app:
    build: .
    container_name: invoice-system-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=host.docker.internal
      - DB_NAME=invoice_system
      - DB_USER=root
      - DB_PASS=
    restart: unless-stopped
